# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytrack < Formula
  desc "A fun CLI-based time/habit tracker"
  homepage "https://github.com/master-wayne7/lazytrack"
  version "1.0.0"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/master-wayne7/lazytrack/releases/download/v1.0.0/lazytrack_Darwin_x86_64.tar.gz"
      sha256 "e0eecc7010e5406ae40e3df3e9d09e05627fc8fee288505311c20289eaff2d06"

      def install
        bin.install "lazytrack"
      end
    end
    on_arm do
      url "https://github.com/master-wayne7/lazytrack/releases/download/v1.0.0/lazytrack_Darwin_arm64.tar.gz"
      sha256 "7c392baf299782052f5c594dc493dd9e861c08c316e3fb1ceb82f60f25f30925"

      def install
        bin.install "lazytrack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/master-wayne7/lazytrack/releases/download/v1.0.0/lazytrack_Linux_x86_64.tar.gz"
        sha256 "04297e14eb9e681c82551830c0bd9b0f0967c25cf280fd40d888e13a299e78f6"

        def install
          bin.install "lazytrack"
        end
      end
    end
  end

  test do
    system "#{bin}/lazytrack", "--help"
  end
end
